### ISSUE TITLE
shell 写爬虫多并发效率如何。

### ISSUE THREAD

**Issue by yanguanglan** [gfdhgfnd/chicken-ribs#1]
如何支持异步回调。

**Comment by gfdhgfnd** [comment]
好像不支持异步回调，而且效率也不高，跟其它语言相比唯一的优势大概就在于语法很简练（开箱即用貌似也算一个？）。

**Comment by yanguanglan** [comment]
简练吸引到我了。哈哈！看着很多特殊字符。

**Comment by gfdhgfnd** [comment]
偶尔用用还可以，但shell不擅长这个，用着感觉很重，很耗资源，推荐perl和ruby
